version: 2

models:
  - name: silver_customers_orders
    description: "Cleaned customer order and product-level data"
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null

  - name: gold_customer_summary
    description: "Customer-level business summary"
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: total_orders
        tests:
          - not_null
      - name: total_spent
        tests:
          - not_null
